### Detect OS/Arch

if(UNIX)
  set(SYS_UNIX TRUE)
endif()

if(WIN32)
  set(SYS_WINDOWS TRUE)
endif()

if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(SYS_LINUX TRUE)
    set(SYS_UNIX TRUE)
endif()

### Detect Compiler

if(MSVC OR MSVC_IDE OR CMAKE_COMPILER_2005 OR CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  set(COMP_CL TRUE)
elseif(CMAKE_CXX_COMPILER MATCHES ".*clang[+][+]" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set(COMP_CLANG TRUE)
  set(COMP_GCCLIKE TRUE)
elseif(CMAKE_CXX_COMPILER MATCHES ".*icpc" OR CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
  set(COMP_ICC TRUE)
  set(COMP_GCCLIKE TRUE)
elseif(CMAKE_COMPILER_IS_GNUCXX)
  set(COMP_GCC TRUE)
  set(COMP_GCCLIKE TRUE)
endif()
