
macro(def_lib target)
  cmake_parse_arguments(THIS "" "" "SOURCES;DEPEND;LIB_DEPEND" ${ARGN})
  add_library(${target} ${THIS_SOURCES})
  target_compile_definitions(${target} PUBLIC ${GLOBAL_DEFINES})
  target_compile_options(${target} PUBLIC ${GLOBAL_FLAGS})
  target_link_options(${target} PUBLIC ${GLOBAL_LINK_FLAGS})
  if(THIS_DEPEND)
    target_link_libraries(${target} ${THIS_DEPEND})
  endif()
  if(THIS_LIB_DEPEND)
    target_link_libraries(${target} ${THIS_LIB_DEPEND})
  endif()
  if(HAVE_IPO)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()
endmacro()

macro(def_program target)
  cmake_parse_arguments(THIS "" "" "SOURCES;DEPEND;LIB_DEPEND" ${ARGN})
  add_executable(${target} ${THIS_SOURCES})
  target_compile_definitions(${target} PUBLIC ${GLOBAL_DEFINES})
  target_compile_options(${target} PUBLIC ${GLOBAL_FLAGS})
  target_link_options(${target} PUBLIC ${GLOBAL_LINK_FLAGS})
  if(THIS_DEPEND)
    target_link_libraries(${target} ${THIS_DEPEND})
  endif()
  if(THIS_LIB_DEPEND)
      target_link_libraries(${target} ${THIS_LIB_DEPEND})
  endif()
  target_compile_definitions(${target} PRIVATE -DCMAKE_CURRENT_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
  if(HAVE_IPO)
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()
endmacro()
