
macro(def_lib target)
  cmake_parse_arguments(THIS "" "" "SOURCES;DEPEND;LIB_DEPEND" ${ARGN})
  add_library(${target} ${THIS_SOURCES})
  if(THIS_DEPEND)
    target_link_libraries(${target} ${THIS_DEPEND})
  endif()
  if(THIS_LIB_DEPEND)
      target_link_libraries(${target} ${THIS_LIB_DEPEND})
  endif()
endmacro()

macro(def_program target)
  cmake_parse_arguments(THIS "" "" "SOURCES;DEPEND;LIB_DEPEND" ${ARGN})
  add_executable(${target} ${THIS_SOURCES})
  if(THIS_DEPEND)
    target_link_libraries(${target} ${THIS_DEPEND})
  endif()
  if(THIS_LIB_DEPEND)
      target_link_libraries(${target} ${THIS_LIB_DEPEND})
  endif()
  target_compile_definitions(${target} PRIVATE -DCMAKE_CURRENT_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
endmacro()
